---
- name: 배포판 별로 웹서버 설치하기
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: tasks in Amazon
      include_tasks: amazon.yaml
      when: ansible_distribution == 'Amazon'

    - name: tasks in Ubuntu
      include_tasks: ubuntu.yaml
      when: ansible_distribution == 'Ubuntu'

    - name: PRINT IP ADDRESS
      debug:
        msg:
          - "NodeName : {{ ansible_nodename }}"
          - "eth0: {{ ansible_eth0.ipv4.address }}"
