---
- name: 웹서버설치
  hosts: seoul
  gather_facts: false
  become: true
  tasks:
    - name: install git
      yum:
        name: git
        state: latest

    - name: install httpd
      yum:
        name: httpd
        state: latest

    - name: httpd 시작
      service:
        name: httpd
        state: started

    - name: httpd 포트 변경
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen\s+'
        line: 'Listen 80'
      notify:
        - restart httpd


  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
        enabled: true

